# Generated by Django 4.2 on 2023-04-12 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='chat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 2, 10, 49, 186943)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 2, 10, 49, 187948)),
        ),
    ]
